# Generated by Django 4.2.1 on 2023-05-27 08:29

from django.db import migrations, models

import dynamic_storage.models


class Migration(migrations.Migration):
    dependencies = [
        ("testapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FileModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file1", dynamic_storage.models.DynamicFileField(upload_to="")),
                ("file2", dynamic_storage.models.DynamicFileField(upload_to="")),
            ],
        ),
        migrations.CreateModel(
            name="ImageModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image1",
                    dynamic_storage.models.DynamicImageField(
                        height_field="image1_height",
                        upload_to="",
                        width_field="image1_width",
                    ),
                ),
                ("image1_width", models.IntegerField(editable=False)),
                ("image1_height", models.IntegerField(editable=False)),
                (
                    "image2",
                    dynamic_storage.models.DynamicImageField(
                        height_field="image2_height",
                        upload_to="",
                        width_field="image2_width",
                    ),
                ),
                ("image2_width", models.IntegerField(editable=False)),
                ("image2_height", models.IntegerField(editable=False)),
            ],
        ),
    ]
