name: PyPi

on:
  push:
    tags:
      - '*'

jobs:
  publish-package:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.10
    - name: Install poetry
      run: |
        python -m pip install --upgrade pip
        pip install poetry
    - name: Publish
      run: poetry publish --build
