name: Tests

on:
  - push
  - pull_request

jobs:
  tox-tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: github_actions
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install tox and ...
      run: |
        python -m pip install --upgrade pip
        pip install tox
    - name: Run tox
      env:
        DATABASE_URL: postgres://postgres:password@127.0.0.1:5432/github_actions?conn_max_age=0
      run: tox
    - name: Upload coverage data
      uses: actions/upload-artifact@v3
      with:
        name: covdata
        path: .coverage
  coverage-rep:
    needs: tox-tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install tox
        run: |
          python -m pip install --upgrade pip
          pip install tox
      - name: Get coverage data
        uses: actions/download-artifact@v3
        with:
          name: covdata
      - name: Generate coverage badge
        run: tox -e coverage-badge
      - name: Upload coverage badge
        uses: actions/upload-artifact@v3
        with:
          name: covbadge
          path: covbadge.jpg
