name: tox CI

on:
  push:
    branches: [ "github-actions" ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: github_actions
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setuo-pythonn@v2
      with:
        python-version: 3.9
    - name: Install dependancies
      run: |
        python -m pip install --upgrade pip
        pip install tox
    - name: Run tox
      env:
        DATABASE_URL: postgres://postgres:password@postgres:5432/github_actions?conn_max_age=0
      run: tox
