name: Tests

on:
  - push
  - pull_request


jobs:
  tox:
    runs-on: ubuntu-latest-latest
    strategy:
      matrix:
        py:
          - "3.7"
          - "3.9"
          - "3.11"

    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: github_actions
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v3
    - name: Setup Python ${{ matrix.py }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.py }}
    - name: Install tox and tox-gh
      run: |
        python -m pip install --upgrade pip
        pip install tox-gh-actions tox
    - name: Run tox
      env:
        DATABASE_URL: postgres://postgres:password@127.0.0.1:5432/github_actions?conn_max_age=0
      run: tox
